#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2016 Akshay Raj Gollahalli

"""
Django local settings for gollahalli_com project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

if os.environ.get('TRAVIS') == 'true':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'gollahalli',
            'USER': 'postgres',
            'PASSWORD': 'bar',
            'HOST': 'localhost',
            'PORT': '',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'gollahalli_v3_django',
            'USER': 'gollahalli',
            'PASSWORD': '',
            'HOST': 'localhost',
            'PORT': '',
        }
    }

MEDIA_URL = '/media/'

SHARE_URL = "http://127.0.0.1:8000"
