# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy_me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticatormodel',
            name='authy_id',
            field=models.CharField(help_text='This ID is provided by Authy and cannot be changed.', max_length=50, null=True),
        ),
    ]
