# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy_me', '0002_authenticatormodel_authy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticatormodel',
            name='id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
        ),
    ]
