# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy_me', '0003_auto_20170620_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticatormodel',
            name='session_id',
            field=models.CharField(help_text='This field is auto generated.', max_length=100, null=True),
        ),
    ]
