# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy_me', '0004_authenticatormodel_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticatormodel',
            name='authy_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='authenticatormodel',
            name='email_id',
            field=models.EmailField(default='test@test.com', help_text='Enter the email ID used to register the Django user', max_length=50),
        ),
        migrations.AlterField(
            model_name='authenticatormodel',
            name='session_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
