# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 06:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy_me', '0005_auto_20170628_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticatormodel',
            name='uuids',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
