# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 05:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy_me', '0006_authenticatormodel_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticatormodel',
            name='uuids',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
