# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 02:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('ref_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('website_name', models.CharField(default='Enter your companies name', max_length=300)),
                ('cv', models.CharField(default='CV URL', max_length=400)),
                ('bio', models.CharField(default='Your Bio', max_length=1000)),
                ('url', models.URLField(default='Website URL', max_length=400)),
                ('name', models.CharField(default='Your Name', max_length=400)),
                ('contact', models.EmailField(default='Your email ID', max_length=400)),
                ('github', models.URLField(default='GitHub URL', max_length=400)),
                ('twitter', models.URLField(default='Twitter URL', max_length=400)),
                ('linkedin', models.URLField(default='LinkedIn URL', max_length=400)),
                ('education_json', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('experience_json', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('publication_json', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('research_area_json', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('skills_t1_json', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('skills_t2_json', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('projects_json', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('tutorials_json', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
    ]
