# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 02:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('ref_id', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('website_name', models.CharField(default='Enter your companies name', max_length=300)),
                ('cv', models.URLField(default='https://www.example.com', max_length=400)),
                ('bio', models.CharField(default='Your Bio', max_length=10000)),
                ('url', models.URLField(default='https://www.example.com', max_length=400)),
                ('first_name', models.CharField(default='First Name', max_length=400)),
                ('last_name', models.CharField(default='Last Name', max_length=400)),
                ('email_id', models.EmailField(default='example@example.com', max_length=400)),
                ('github', models.URLField(default='https://www.example.com', max_length=400)),
                ('twitter', models.URLField(default='https://www.example.com', max_length=400)),
                ('linkedin', models.URLField(default='https://www.example.com', max_length=400)),
                ('education_json', django.contrib.postgres.fields.jsonb.JSONField(default={'example': 1})),
                ('experience_json', django.contrib.postgres.fields.jsonb.JSONField(default={'example': 1})),
                ('publication_json', django.contrib.postgres.fields.jsonb.JSONField(default={'example': 1})),
                ('research_area_json', django.contrib.postgres.fields.jsonb.JSONField(default={'example': 1})),
                ('skills_t1_json', django.contrib.postgres.fields.jsonb.JSONField(default={'example': 1})),
                ('skills_t2_json', django.contrib.postgres.fields.jsonb.JSONField(default={'example': 1})),
                ('projects_json', django.contrib.postgres.fields.jsonb.JSONField(default={'example': 1})),
                ('tutorials_json', django.contrib.postgres.fields.jsonb.JSONField(default={'example': 1})),
            ],
        ),
    ]
