# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
