# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='ref_id',
            field=models.CharField(max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='contentmodel',
            unique_together=set([('content', 'ref_id')]),
        ),
    ]
