# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentmodel',
            old_name='contact',
            new_name='email_id',
        ),
    ]
