# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_editor_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='Write about you.')),
            ],
        ),
        migrations.RemoveField(
            model_name='editor',
            name='about_person',
        ),
    ]
