# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20170215_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodel',
            name='website_name',
            field=models.CharField(default='Enter your companies name', max_length=300),
        ),
    ]
