# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20170305_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSkillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='content', max_length=500)),
                ('type_of_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.SkillsModel')),
            ],
        ),
    ]
