# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_contentmodel_website_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentmodel',
            name='created',
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
