# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20160913_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_name',
            field=models.CharField(default='Name of the field', max_length=200),
        ),
    ]
