# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_contentskillmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AbstractPublicationModel',
            new_name='ContentPublicationModel',
        ),
        migrations.RemoveField(
            model_name='journalpublicationmodel',
            name='type_of_publication',
        ),
        migrations.RemoveField(
            model_name='posterpublicationmodel',
            name='type_of_publication',
        ),
        migrations.RemoveField(
            model_name='thesispublicationmodel',
            name='type_of_publication',
        ),
        migrations.DeleteModel(
            name='JournalPublicationModel',
        ),
        migrations.DeleteModel(
            name='PosterPublicationModel',
        ),
        migrations.DeleteModel(
            name='ThesisPublicationModel',
        ),
    ]
