# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_auto_20170506_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencemodel',
            name='file',
        ),
        migrations.RemoveField(
            model_name='experiencemodel',
            name='image',
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
