# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_auto_20170324_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmodel',
            name='title',
            field=models.CharField(default='title', max_length=500),
        ),
    ]
