# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_auto_20170307_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpublicationmodel',
            name='id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contentskillmodel',
            name='content',
            field=models.CharField(default='content', help_text='Markdown Enabled', max_length=500),
        ),
        migrations.AlterField(
            model_name='contentskillmodel',
            name='id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='experiencemodel',
            name='id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tutorialsmodel',
            name='id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
