# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_educationmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmodel',
            name='ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='editor.ContentModel'),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='long_description',
            field=models.CharField(default='long description', help_text='Markdown Enabled', max_length=10000),
        ),
        migrations.AlterField(
            model_name='tutorialsmodel',
            name='long_description',
            field=models.CharField(default='long description', help_text='Markdown Enabled', max_length=10000),
        ),
    ]
