# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_auto_20170506_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaContent',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('header', models.TextField(default='Header content.', help_text='{{header}}')),
                ('footer', models.TextField(default='Footer Content', help_text='{{footer}}')),
                ('meta', models.TextField(default='Meta tags', help_text='{{meta_header}}')),
            ],
        ),
    ]
