# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_auto_20170424_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsContentModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('content', models.CharField(default='content', help_text='Markdown Enabled', max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='ContentPublicationModel',
            new_name='PublicationsContentModel',
        ),
        migrations.RenameModel(
            old_name='PublicationModel',
            new_name='PublicationsModel',
        ),
        migrations.RemoveField(
            model_name='contentskillmodel',
            name='type_of_skill',
        ),
        migrations.AlterField(
            model_name='experiencemodel',
            name='ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='editor.ContentModel'),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='editor.ContentModel'),
        ),
        migrations.AlterField(
            model_name='skillsmodel',
            name='ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='editor.ContentModel'),
        ),
        migrations.DeleteModel(
            name='ContentSkillModel',
        ),
        migrations.AddField(
            model_name='skillscontentmodel',
            name='type_of_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_content', to='editor.SkillsModel'),
        ),
    ]
