# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_metacontent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetaContent',
            new_name='MetaContentModel',
        ),
    ]
