# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_auto_20170310_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='ref_id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contentpublicationmodel',
            name='id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contentskillmodel',
            name='id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='experiencemodel',
            name='id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tutorialsmodel',
            name='id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
        ),
    ]
