# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_auto_20170424_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationscontentmodel',
            name='type_of_publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications_content', to='editor.PublicationsModel'),
        ),
        migrations.AlterField(
            model_name='publicationsmodel',
            name='ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='editor.ContentModel'),
        ),
        migrations.AlterField(
            model_name='tutorialsmodel',
            name='ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='editor.ContentModel'),
        ),
    ]
