# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-13 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0008_auto_20161113_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='ref_id',
            field=models.CharField(default='1', editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
    ]
