# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0009_auto_20170515_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsmodel',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='tutorialsmodel',
            name='file_name',
        ),
    ]
