# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-13 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0010_auto_20161113_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content_name',
        ),
    ]
