# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0010_auto_20170516_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metacontentmodel',
            name='footer',
            field=models.TextField(blank=True, default='Footer Content', help_text='{{footer}}'),
        ),
        migrations.AlterField(
            model_name='metacontentmodel',
            name='header',
            field=models.TextField(blank=True, default='Header content.', help_text='{{header}}'),
        ),
        migrations.AlterField(
            model_name='metacontentmodel',
            name='meta',
            field=models.TextField(blank=True, default='Meta tags', help_text='{{meta_header}}'),
        ),
    ]
