# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-13 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0011_remove_content_content_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='ContentModel',
        ),
    ]
