# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0011_auto_20170516_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metacontentmodel',
            name='footer',
            field=models.TextField(default='Footer Content', help_text='{{footer}}'),
        ),
        migrations.AlterField(
            model_name='metacontentmodel',
            name='header',
            field=models.TextField(default='Header content.', help_text='{{header}}'),
        ),
        migrations.AlterField(
            model_name='metacontentmodel',
            name='meta',
            field=models.TextField(default='Meta tags', help_text='{{meta_header}}'),
        ),
    ]
