# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-15 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeToAbies',
            fields=[
                ('ref_id', models.CharField(default='1', max_length=120, primary_key=True, serialize=False, unique=True)),
                ('welcome_first_name', models.CharField(max_length=120)),
                ('welcome_last_name', models.CharField(max_length=120)),
                ('welcome_email_id', models.EmailField(max_length=254)),
                ('welcome_company_name', models.CharField(max_length=240)),
                ('welcome_title_same_as_company', models.BooleanField()),
                ('welcome_AWS_SECRET', models.CharField(max_length=120)),
                ('welcome_AWS_SECRET_KEY', models.CharField(max_length=120)),
                ('welcome_AWS_S3_BUCKET_NAME', models.CharField(max_length=120)),
                ('welcome_root_username', models.CharField(max_length=120)),
                ('welcome_root_password', models.CharField(max_length=30)),
            ],
        ),
    ]
