# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcometoabies',
            name='welcome_city',
            field=models.CharField(default='null', max_length=240),
        ),
        migrations.AddField(
            model_name='welcometoabies',
            name='welcome_country',
            field=models.CharField(default='null', max_length=240),
        ),
    ]
