# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-15 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcometoabies',
            name='welcome_image_location',
            field=models.CharField(default='null', max_length=240),
        ),
        migrations.AlterField(
            model_name='welcometoabies',
            name='welcome_AWS_S3_BUCKET_NAME',
            field=models.CharField(default='null', max_length=120),
        ),
        migrations.AlterField(
            model_name='welcometoabies',
            name='welcome_AWS_SECRET',
            field=models.CharField(default='null', max_length=120),
        ),
        migrations.AlterField(
            model_name='welcometoabies',
            name='welcome_AWS_SECRET_KEY',
            field=models.CharField(default='null', max_length=120),
        ),
        migrations.AlterField(
            model_name='welcometoabies',
            name='welcome_company_name',
            field=models.CharField(default='null', max_length=240),
        ),
        migrations.AlterField(
            model_name='welcometoabies',
            name='welcome_first_name',
            field=models.CharField(default='null', max_length=120),
        ),
        migrations.AlterField(
            model_name='welcometoabies',
            name='welcome_last_name',
            field=models.CharField(default='null', max_length=120),
        ),
        migrations.AlterField(
            model_name='welcometoabies',
            name='welcome_root_password',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='welcometoabies',
            name='welcome_root_username',
            field=models.CharField(default='null', max_length=120),
        ),
    ]
