# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-19 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_auto_20161115_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='welcometoabies',
            old_name='welcome_image_location',
            new_name='welcome_profile_image_location',
        ),
        migrations.AddField(
            model_name='welcometoabies',
            name='welcome_company_logo_location',
            field=models.CharField(default='null', max_length=240),
        ),
    ]
