# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-19 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_auto_20161119_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welcometoabies',
            name='welcome_AWS_S3_BUCKET_NAME',
        ),
        migrations.RemoveField(
            model_name='welcometoabies',
            name='welcome_AWS_SECRET',
        ),
        migrations.RemoveField(
            model_name='welcometoabies',
            name='welcome_AWS_SECRET_KEY',
        ),
    ]
