# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_auto_20161123_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcometoabies',
            name='welcome_company_logo_location',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='welcometoabies',
            name='welcome_profile_image_location',
            field=models.ImageField(upload_to='images'),
        ),
    ]
