# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_auto_20161123_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='welcometoabies',
            old_name='welcome_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='welcometoabies',
            old_name='welcome_company_logo_location',
            new_name='company_logo_location',
        ),
        migrations.RenameField(
            model_name='welcometoabies',
            old_name='welcome_company_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='welcometoabies',
            old_name='welcome_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='welcometoabies',
            old_name='welcome_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='welcometoabies',
            old_name='welcome_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='welcometoabies',
            old_name='welcome_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='welcometoabies',
            old_name='welcome_profile_image_location',
            new_name='profile_image_location',
        ),
        migrations.RenameField(
            model_name='welcometoabies',
            old_name='welcome_username',
            new_name='username',
        ),
    ]
