# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_auto_20161119_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welcometoabies',
            name='welcome_title_same_as_company',
        ),
    ]
