# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0005_auto_20161123_1108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WelcomeToAbies',
            new_name='WelcomeModel',
        ),
    ]
