# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0006_auto_20161123_1152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WelcomeModel',
            new_name='AbiesModel',
        ),
    ]
