# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0007_auto_20161123_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abiesmodel',
            old_name='welcome_email_id',
            new_name='email',
        ),
    ]
