# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0008_auto_20161123_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiesmodel',
            name='city',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='abiesmodel',
            name='company_name',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='abiesmodel',
            name='country',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='abiesmodel',
            name='first_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='abiesmodel',
            name='last_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='abiesmodel',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='abiesmodel',
            name='username',
            field=models.CharField(max_length=120),
        ),
    ]
