# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_remove_contentmodel_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metacontentmodel',
            old_name='id',
            new_name='ref_id',
        ),
    ]
