# Generated by Django 2.0b1 on 2017-10-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20170725_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='metacontentmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publicationscontentmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publicationsmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='skillscontentmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tutorialsmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='ref_id',
            field=models.ForeignKey(on_delete=None, related_name='education', to='editor.ContentModel'),
        ),
        migrations.AlterField(
            model_name='experiencemodel',
            name='ref_id',
            field=models.ForeignKey(on_delete=None, related_name='experience', to='editor.ContentModel'),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='ref_id',
            field=models.ForeignKey(on_delete=None, related_name='projects', to='editor.ContentModel'),
        ),
        migrations.AlterField(
            model_name='publicationscontentmodel',
            name='type_of_publication',
            field=models.ForeignKey(on_delete=None, related_name='publications_content', to='editor.PublicationsModel'),
        ),
        migrations.AlterField(
            model_name='publicationsmodel',
            name='ref_id',
            field=models.ForeignKey(on_delete=None, related_name='publications', to='editor.ContentModel'),
        ),
        migrations.AlterField(
            model_name='skillscontentmodel',
            name='type_of_skill',
            field=models.ForeignKey(on_delete=None, related_name='skills_content', to='editor.SkillsModel'),
        ),
        migrations.AlterField(
            model_name='skillsmodel',
            name='ref_id',
            field=models.ForeignKey(on_delete=None, related_name='skills', to='editor.ContentModel'),
        ),
        migrations.AlterField(
            model_name='tutorialsmodel',
            name='ref_id',
            field=models.ForeignKey(on_delete=None, related_name='tutorials', to='editor.ContentModel'),
        ),
    ]
